language: python
python:
  - "3.6"

# You will also need the SOCH_API_KEY variable set in Travis
install: pip install pipenv && pipenv install --dev --three
script: pipenv run python3 source/index.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: output
  target-branch: gh-pages
